# Data transformation

The datasets are all under the dataset folder (./dataset), and we will discuss the data cleaning/transformation of each dataset in details below:

<b>*Health Data</b> (./dataset/Covid): the data is in good shape as it is. We only changed the column names, replacing blank spaces with underscores for better R compatibility.

<b>*Political Data</b> (./dataset/Election): the data is also clean and we only changed the column names, replacing blank spaces and abbreviated election candidate names. The political data contains a few missing values and we will explain how to deal with those in chapter 4. We will omit the total count rows, which leaves us 62 rows corresponding to 62 county observations.

<b>*Economic Data</b> (./dataset/Income): the economic data is gathered from US census bureau, thus the margin of error is provided for each column. After careful observation, we decided that the margin of error is trivial comparing to the reported numbers and thus we can omit the margin errors in our exploratory data analysis. The dataset is transposed to have counties in rows and variables in columns. Same column name replacement is performed to have better compatibility with R. We also deleted sub-columns corresponding to economic data of demographic subgroups. We believe that if the bin size is too small, the patterns will be less obvious in the exploratory visualization. The data has lots of missing values and we will explain how to deal with it in chapter 4 missing values.

<b>*Geographic Data</b> (./dataset/Map): this is a shapefile that can be imported with <b>rgdal</b> package in R.

<b>*Demographic Data</b> (./dataset/Race): the demographic data is collected from US census bureau. The same margin of error omittance, column name replacement, and table transposition are performed.

<b>*Labor Mobility Data</b> (./dataset/Work_Residence): the labor data is collected from US census bureau. The same margin of error omittance, column name replacement, and table transposition are performed. We also deleted sub-columns that corresponds to categories that are too subdivided.

<b>*X_Variable Data</b> (./dataset/X): After cleaning the datasets listed above, we have obtained five different datasets (Health, Political, Economic, Geographic, and Demographic) that share same 62 indexes corresponding to 62 index county. We merge all five datasets by county index into one big X_Variable dataset which is more user-friendly. The suffix of county index names are removed so that index names are compatible with the geo-information inside NYS shapefile.